### ISSUE TITLE
Coherence increases despite increasing fragmentation

### ISSUE THREAD

**Issue by HeiKima** [MathieuChailloux/FragScape#6]
Hi,
More a question than an issue.
Using the CBC method it occurs in some cases that the coherence (or rather probability) is lower for less fragmented scenarios than for more fragmented. Calculating the coherence for a 0-Case scenario without any roads the result is:

nb_patches: 3
reportarea: 100000000
intersecting: 6516029,456
effective mesh size: 44663524,28
coherence: 0,010697887

in compare to the scenario with roads

nb_patches: 8
reportarea: 100000000
intersecting: 6460566,108
effective mesh size: 5801795,57
coherence: 0,011004789

How is this possible? Maybe I don't get the maths behind it?
Hope you can help me out here.

Greetings
HK

**Comment by MathieuChailloux** [comment]
Hi,
Indeed this is confusing.
In CBC mode, you should juste consider effective mesh size and net product.
Other metrics (coherence, splitting index, splitting density and landscape division) are irrelevant in such mode.

This shall be fixed in next published version to avoid such confusion, sorry for this.

Regards,
Mathieu

**Comment by MathieuChailloux** [comment]
Fixed in 2.0 (only 2 CBC metrics : CBC_effective_mesh_size and CBC_net_product)
